### ISSUE TITLE
Error on generate

### ISSUE THREAD

**Issue by sujit-baniya** [thedevsbuddy/adminr#1]
After doing npm run production, the styles are OFF.

![image](https://user-images.githubusercontent.com/4959215/164873033-ff3a84c7-e0e1-4271-a4e4-64a178a103c4.png)

And unable to generate from builder as it's getting error
![image](https://user-images.githubusercontent.com/4959215/164873021-321d5e39-7975-4104-907a-f0d6962a9810.png)

**Comment by thedevsbuddy** [comment]
Thanks for your feedback I am working on it to solve the issue and also same time updating to use Laravel v9.x. 
Soon it will be fixed and updated.

**Comment by thedevsbuddy** [comment]
> 

For the error on generate you may have not configured `ADMINR_ROUTE_PREFIX` in `.env` file because as shown in your screenshot the requested route is `http://127.0.0.1:8000//generate` but it should be  `http://127.0.0.1:8000/<ADMINR_ROUTE_PREFIX>/generate` try by configuring prefix. it may solve the generation issue.

**Comment by thedevsbuddy** [comment]
Updated to latest version of laravel and PHP syntax #3
